name: Android MasterApp Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Master APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@4

      - name: Set up JDK 11
        uses: actions/setup-java@4
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Set up Gradle
        uses: gradle/gradle-build-action@3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK (Release)
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@3
        with:
          name: MasterApp-Release-APK
          path: app/build/outputs/apk/release/app-release.apk
